# Generated by Django 3.1.7 on 2021-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_log_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customquestionlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
