version: "3.8"
services:
  db:
    image: "postgres:13"
    environment:
      - "POSTGRES_PASSWORD=d122da0c-7aa0-4579-8607-f7d007eb4d83"
      - "POSTGRES_DB="
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - db

  redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      default:
        aliases:
          - redis

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    # example for Django + postgres
    command: >
      bash -c "wait-for-it -t 0 db:5432 &&
      printf 'yes' | python /code/manage.py collectstatic &&
      python /code/manage.py migrate &&
      python -m uvicorn settings.asgi:application --reload --host 0.0.0.0 --port 8000 --log-level info --use-colors"
    environment:
      - database_host=db
    volumes:
      - type: bind
        source: ./backend/
        target: /code
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - api

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    depends_on:
      - backend

    networks:
      default:
        aliases:
          - frontend

volumes:
  frontend:
  node_modules:
  psql:
