enum WS_MESSAGE_TYPES {
    CONNECT = 'CONNECT',
    SEND_GENERIC = 'SEND_GENERIC',
    SEND_EVENT = 'SEND_EVENT',
    DISCONNECT = 'DISCONNECT',
    REGISTER = 'REGISTER',
}
export default WS_MESSAGE_TYPES;
